//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW21Factory
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FactoryEntities : DbContext
    {
        public FactoryEntities()
            : base("name=FactoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InvoiceOnInput> InvoiceOnInputs { get; set; }
        public virtual DbSet<Movement> Movements { get; set; }
        public virtual DbSet<PriceDictionary> PriceDictionaries { get; set; }
        public virtual DbSet<RequiermentOnOutput> RequiermentOnOutputs { get; set; }
    
        public virtual ObjectResult<MainDetailInfo_Result> MainDetailInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MainDetailInfo_Result>("MainDetailInfo");
        }
    
        public virtual int AddDetail(Nullable<int> detailID, string detailName, Nullable<int> detailCount)
        {
            var detailIDParameter = detailID.HasValue ?
                new ObjectParameter("DetailID", detailID) :
                new ObjectParameter("DetailID", typeof(int));
    
            var detailNameParameter = detailName != null ?
                new ObjectParameter("DetailName", detailName) :
                new ObjectParameter("DetailName", typeof(string));
    
            var detailCountParameter = detailCount.HasValue ?
                new ObjectParameter("DetailCount", detailCount) :
                new ObjectParameter("DetailCount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddDetail", detailIDParameter, detailNameParameter, detailCountParameter);
        }
    
        public virtual int AddDetailPrice(Nullable<int> detailID, Nullable<decimal> price)
        {
            var detailIDParameter = detailID.HasValue ?
                new ObjectParameter("DetailID", detailID) :
                new ObjectParameter("DetailID", typeof(int));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddDetailPrice", detailIDParameter, priceParameter);
        }
    
        public virtual int AddInvoice(Nullable<int> invoiceID, Nullable<int> detailID, Nullable<int> inputCount, Nullable<System.DateTime> dateOfInput)
        {
            var invoiceIDParameter = invoiceID.HasValue ?
                new ObjectParameter("InvoiceID", invoiceID) :
                new ObjectParameter("InvoiceID", typeof(int));
    
            var detailIDParameter = detailID.HasValue ?
                new ObjectParameter("DetailID", detailID) :
                new ObjectParameter("DetailID", typeof(int));
    
            var inputCountParameter = inputCount.HasValue ?
                new ObjectParameter("InputCount", inputCount) :
                new ObjectParameter("InputCount", typeof(int));
    
            var dateOfInputParameter = dateOfInput.HasValue ?
                new ObjectParameter("DateOfInput", dateOfInput) :
                new ObjectParameter("DateOfInput", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddInvoice", invoiceIDParameter, detailIDParameter, inputCountParameter, dateOfInputParameter);
        }
    
        public virtual int AddRequirement(Nullable<int> requirementID, Nullable<int> detailID, Nullable<int> outputCount, Nullable<System.DateTime> dateOfOutput)
        {
            var requirementIDParameter = requirementID.HasValue ?
                new ObjectParameter("RequirementID", requirementID) :
                new ObjectParameter("RequirementID", typeof(int));
    
            var detailIDParameter = detailID.HasValue ?
                new ObjectParameter("DetailID", detailID) :
                new ObjectParameter("DetailID", typeof(int));
    
            var outputCountParameter = outputCount.HasValue ?
                new ObjectParameter("OutputCount", outputCount) :
                new ObjectParameter("OutputCount", typeof(int));
    
            var dateOfOutputParameter = dateOfOutput.HasValue ?
                new ObjectParameter("DateOfOutput", dateOfOutput) :
                new ObjectParameter("DateOfOutput", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddRequirement", requirementIDParameter, detailIDParameter, outputCountParameter, dateOfOutputParameter);
        }
    
        public virtual int RemoveDetail(Nullable<int> detailID)
        {
            var detailIDParameter = detailID.HasValue ?
                new ObjectParameter("DetailID", detailID) :
                new ObjectParameter("DetailID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RemoveDetail", detailIDParameter);
        }
    
        public virtual int RemoveDetailPrice(Nullable<int> detailID)
        {
            var detailIDParameter = detailID.HasValue ?
                new ObjectParameter("DetailID", detailID) :
                new ObjectParameter("DetailID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RemoveDetailPrice", detailIDParameter);
        }
    
        public virtual int RemoveInvoice(Nullable<int> invoiceID)
        {
            var invoiceIDParameter = invoiceID.HasValue ?
                new ObjectParameter("InvoiceID", invoiceID) :
                new ObjectParameter("InvoiceID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RemoveInvoice", invoiceIDParameter);
        }
    
        public virtual int RemoveRequirement(Nullable<int> requirementID)
        {
            var requirementIDParameter = requirementID.HasValue ?
                new ObjectParameter("RequirementID", requirementID) :
                new ObjectParameter("RequirementID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RemoveRequirement", requirementIDParameter);
        }
    
        public virtual ObjectResult<CountRemaining_Result> CountRemaining()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CountRemaining_Result>("CountRemaining");
        }
    
        public virtual ObjectResult<GetDetailCost_Result> GetDetailCost()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDetailCost_Result>("GetDetailCost");
        }
    
        public virtual ObjectResult<GetDetailCostOnRequirement_Result> GetDetailCostOnRequirement()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDetailCostOnRequirement_Result>("GetDetailCostOnRequirement");
        }
    
        public virtual ObjectResult<GetInputCountOnMonth_Result> GetInputCountOnMonth(Nullable<int> month)
        {
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInputCountOnMonth_Result>("GetInputCountOnMonth", monthParameter);
        }
    
        public virtual ObjectResult<string> GetNameOfDetail()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetNameOfDetail");
        }
    
        public virtual ObjectResult<MovementOnDate_Result> MovementOnDate(Nullable<System.DateTime> date)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MovementOnDate_Result>("MovementOnDate", dateParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
