//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW21Factory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movement
    {
        public int DetailID { get; set; }
        public string DetailName { get; set; }
        public int DetailCount { get; set; }
    
        public virtual PriceDictionary PriceDictionary { get; set; }
    }
}
