//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW21Factory
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceDictionary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PriceDictionary()
        {
            this.InvoiceOnInputs = new HashSet<InvoiceOnInput>();
            this.RequiermentOnOutputs = new HashSet<RequiermentOnOutput>();
        }
    
        public int DetailID { get; set; }
        public decimal Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceOnInput> InvoiceOnInputs { get; set; }
        public virtual Movement Movement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequiermentOnOutput> RequiermentOnOutputs { get; set; }
    }
}
